### ISSUE TITLE
Add a nice little animation when hovering over the navbar logo

### ISSUE THREAD

**Issue by Lange** [nodecg/docs#17]
Every link on the site reacts to hover state EXCEPT this one.

Lately, there has been a trend where the navbar logo has a cute little anim when hovered, and I think it'd be a nice bit of polish if we followed suit. Twitch is a good example of this: 
![ezgif-6-e6a9b3ac002e](https://user-images.githubusercontent.com/873012/75600551-2153c400-5a76-11ea-8841-9dfca5307728.gif)

**Comment by mkrl** [comment]
It's hard to animate something that's not vector. Here's a simple redraw of NodeCG logo in Figma, might come in handy for something else. Not too sure if it already exists, but I failed to find any source images for the logo.
https://www.figma.com/file/7PQfD4VKzktQ89jWio7cCs/NodeCG?node-id=0%3A1

Here's what came to my mind for the animation. I can't think of any text effects that will be noticeable enough on that navbar logo sale.

https://www.figma.com/proto/7PQfD4VKzktQ89jWio7cCs/NodeCG?node-id=9%3A31&scaling=min-zoom

**Comment by Lange** [comment]
Oh nice, @chrishanel was also working on a vectorization of the logo

**Comment by Lange** [comment]
@mkrl sure, I'm okay with this anim, a PR would be lovely

**Comment by mkrl** [comment]
After further investigation, I took a look at Docusaurus theming docs.
https://v2.docusaurus.io/docs/using-themes/#swizzling-theme-components

The only good way to have the logo animated is to replace it with inline SVG, which can be done, but only by "ejecting" base theme components from the built-in theme. It can be done, but it's strongly advised not to do so (at least not until Docusaurus is at least at its' beta stage), because in this case may get stuck with broken navbar when the upstream theme changes.

Here is a branch with the logo animated on hover https://github.com/mkrl/docs-1/tree/new-logo
Either way, the effect is still barely visible at this scale. 

![GIF with NodeCG logo growing on mouse hover](https://user-images.githubusercontent.com/18409292/76173279-cbce9400-61a6-11ea-9b93-4d7d726bdb72.gif)

**Comment by Lange** [comment]
Ah okay, yeah swizzling just to get this logo animation in is not worth it. Thanks for investigating it though!
